# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11fa1ae934612f26a91fb8365be42afa871b63f456b21c77c4c76e3270015b1959126fa8f31de413661e92e121e1231a3b80f5d19a64445440a662caa6edf334

test:
  secret_key_base: b2ea61fdbc3b53f1c9b18763c6d1bec19ca9d60a876916546a2a4f96dde3fb94e5db0b1bf48e2b034681a8f2d19d829f2b55e7e377363cec831baa1c5d97fb98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
